AIBlockOfficial/Chain

Cargo.lock
Cargo.toml
README.md

Setting the repo to `0.1.0` and preparing it for a crate publish

Set to 0.1.0 and prepare for crate publishing

---

.github/pull_request_template.md
Cargo.lock
Cargo.toml
src/primitives/druid.rs
src/primitives/transaction.rs
src/utils/druid_utils.rs
src/utils/script_utils.rs
src/utils/transaction_utils.rs

Merge from `develop` into `main`. 
- Adds `fees` attribute to transactions
- Refactors several functions to reduce the number of required arguments
- Adds a PR template for the repo

Merge Develop into Main; Bump version to v1.1.0

---

.github/pull_request_template.md

Adds a timestamp attribute to the block header
- Adds `timestamp` to `BlockHeader`

Merge Develop into Main; Bump to v1.2.0

---

Cargo.lock
Cargo.toml
src/bin/main/db/db_utils.rs
src/bin/main/db/display.rs
src/crypto.rs
src/primitives/block.rs
src/primitives/transaction.rs
src/utils/script_utils.rs

Removes `unwrap` methods from the code, replacing them with sensible `match` handling

Removing Unwraps

---

.github/pull_request_template.md
Cargo.lock
Cargo.toml
src/bin/main/db/db_utils.rs
src/bin/main/db/display.rs
src/crypto.rs
src/primitives/block.rs
src/primitives/transaction.rs
src/utils/script_utils.rs

Merges `develop` into `main` and bumps the version to 1.2.2. 
- Removes panicking events that would disable the chain in prod
- Replaces `panic` and `unwrap` events with defaults or `match` handling

Merge into Develop; Bump to 1.2.2

---

readmes/README.ar.md
readmes/README.de.md
readmes/README.es.md
readmes/README.fr.md
readmes/README.zhs.md
src/bin/main/db/db_utils.rs
src/bin/main/db/display.rs
src/bin/main/main.rs
src/crypto.rs
src/primitives/asset.rs
src/primitives/block.rs
src/utils/druid_utils.rs
src/utils/script_utils.rs
src/utils/transaction_utils.rs

The `Data` asset type doesn't make sense on the chain anymore, so it's best to remove it for future releases
- Removes `Asset::Data` enum and `DataAsset` asset type from the chain structure

Remove data asset

---

Cargo.lock
Cargo.toml
README.md
readmes/README.ar.md
readmes/README.de.md
readmes/README.es.md
readmes/README.fr.md
readmes/README.zhs.md
src/constants.rs
src/primitives/asset.rs
src/primitives/druid.rs
src/primitives/transaction.rs
src/utils/druid_utils.rs
src/utils/script_utils.rs
src/utils/test_utils.rs
src/utils/transaction_utils.rs

Renames everything
- Changes `a_block_chain` to `tw_chain`
- Changes `drs_tx_hash` to `genesis_hash`, along with all variations
- Removes `drs_block_hash`, as it's no longer needed
- Reset the version to 1.0.0, preparing for a new crate

Renaming everything

---

Cargo.lock
Cargo.toml
README.md
readmes/README.ar.md
readmes/README.de.md
readmes/README.es.md
readmes/README.fr.md
readmes/README.zhs.md
src/constants.rs
src/primitives/asset.rs
src/primitives/druid.rs
src/primitives/transaction.rs
src/utils/druid_utils.rs
src/utils/script_utils.rs
src/utils/test_utils.rs
src/utils/transaction_utils.rs

Renames a tonne of different things, including a switch from `a_block_chain` as a crate name to `tw_chain`
- Renames `a_block_chain` to `tw_chain`
- Renames all variations of "ABlock" and "A-Block" to "AIBlock"
- Renames all variations of `drs_tx_hash` to `genesis_hash`
- Removes `drs_block_hash` from the transaction structure
- Fixes documentation in other languages

Merge Develop into Main; Move to tw_chain v1.0.0 🎉

---

src/primitives/block.rs

Adds a `difficulty` placeholder value to block structure
- Adds a `difficulty` placeholder value to block structure

Adding difficulty to block structure

---

Cargo.lock
Cargo.toml
src/utils/druid_utils.rs
src/utils/script_utils.rs
src/utils/transaction_utils.rs

Adds tracing crate for clearer logs
Fixes # (issue number)
Code audit issue #2287010
- Updated tracing crate to v0.1.40
- Replaced all occurences of println!

Adds tracing crate for clearer logs

---

src/utils/mod.rs

Ensures that display formats of values don't overrun the maximum register
- Additional check in display format

Extra check for value in display

---

Cargo.lock
Cargo.toml
src/primitives/transaction.rs
src/utils/script_utils.rs
src/utils/transaction_utils.rs

Adds validation for input signature for payments to a combination of the previous output's transaction hash and all available outputs' addresses.
- Adds validation for input signature for payments to a combination of the previous output's transaction hash and all available outputs' addresses.

Bugfix checksig

---

Cargo.lock
Cargo.toml
src/primitives/transaction.rs
src/utils/mod.rs
src/utils/script_utils.rs
src/utils/transaction_utils.rs

Adds validation for input signature for payments to a combination of the previous output's transaction hash and all available outputs' addresses.
- Adds validation for input signature for payments to a combination of the previous output's transaction hash and all available outputs' addresses.

Merge Develop Into Main; Bump to v1.0.4

---

src/script/interface_ops.rs
src/utils/transaction_utils.rs

Removes JSON string parsing for signed data
- Removes JSON string parsing for signed data

Removing JSON string parsing for signed data

---

src/utils/transaction_utils.rs

Updating check_sig to include the full outputs plus previous outpoint
- Updating check_sig to include the full outputs plus previous outpoint

Updating check_sig to include the full outputs plus previous outpoint

---

Cargo.lock
Cargo.toml
src/utils/transaction_utils.rs

Updating check_sig to include the full outputs plus previous outpoint
- Updating check_sig to include the full outputs plus previous outpoint

Merge Develop into Main; Bump to v1.0.6

---

src/crypto.rs
src/script/interface_ops.rs
src/utils/script_utils.rs
src/utils/test_utils.rs
src/utils/transaction_utils.rs

Removes old validation structure for P2PKH and fixes broken unit tests
- Removes old validation structure for P2PKH and fixes broken unit tests

Remove old validation

---

Cargo.lock
Cargo.toml
src/utils/druid_utils.rs
src/utils/script_utils.rs
src/utils/transaction_utils.rs

Updates transaction construction methods to conform to the security update for checking signatures
- LUpdates transaction construction methods to conform to the security update for checking signatures

Stable passing transaction construction

---

src/primitives/asset.rs
src/utils/druid_utils.rs
src/utils/script_utils.rs
src/utils/transaction_utils.rs

Adds reasoning to the transaction validation process, which will help for debugging purposes from the user endpoints in Network. This is particularly useful if a transaction fails the validation process for some unknown reason and improves user/miner transaction stability
- Adds reasoning to the transaction validation process

Add reasoning to transaction validation process

---

Cargo.lock
Cargo.toml
README.md
readmes/README.ar.md
readmes/README.de.md
readmes/README.es.md
readmes/README.fr.md
readmes/README.zhs.md
src/primitives/asset.rs
src/utils/druid_utils.rs
src/utils/script_utils.rs
src/utils/transaction_utils.rs

Adds reasoning to transaction validation process, improving feedback and robustness
- Adds reasoning to transaction validation process, improving feedback and robustness

Merge Develop into Main; Bump to v1.1.2

---

src/utils/script_utils.rs

Fixes a bug where transactions with zero inputs and/or zero outputs are considered valid by the network
- Fixes a bug where transactions with zero inputs and/or zero outputs are considered valid by the network

Bugfix empty I/O

---

src/primitives/asset.rs
src/primitives/transaction.rs
src/utils/mod.rs
src/utils/script_utils.rs

Checks for valid amounts as per chain limit
Fixes audit finding #2293015
- Checks for valid amounts as per chain limit

Valid amount check
